### ISSUE TITLE
Erste Anmeldung und ViewChange auf BürgerTable löst 401 aus

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#106]
1. GUI Starten
2. Anmelden
3. Auf "Bürger Pflege" klicken

Dies löst folgende Fehlermeldung aus:

```
2015-09-15 15:46:05.454 ERROR 13939 --- [nio-8081-exec-9] reactor.bus.EventBus                     : 401 Unauthorized; nested exception is reactor.core.support.Exceptions$ValueCause: Exception while signaling value: reactor.bus.Event.class : Event{id=null, headers=null, replyTo=null, key=de.muenchen.eventbus.events.AppEvent@0, data=de.muenchen.eventbus.events.AppEvent@0}

org.springframework.web.client.HttpClientErrorException: 401 Unauthorized; nested exception is reactor.core.support.Exceptions$ValueCause: Exception while signaling value: reactor.bus.Event.class : Event{id=null, headers=null, replyTo=null, key=de.muenchen.eventbus.events.AppEvent@0, data=de.muenchen.eventbus.events.AppEvent@0}
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530)
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:476)
    at org.springframework.hateoas.client.Traverson$TraversalBuilder.toObject(Traverson.java:257)
    at de.muenchen.vaadin.demo.api.rest.BuergerRestClientImpl.findAll(BuergerRestClientImpl.java:43)
    at de.muenchen.vaadin.services.BuergerServiceImpl.findAll(BuergerServiceImpl.java:70)
    at de.muenchen.vaadin.ui.controller.BuergerViewController.queryBuerger(BuergerViewController.java:332)
    at de.muenchen.vaadin.ui.controller.BuergerViewController.queryEventHandler(BuergerViewController.java:447)
    at de.muenchen.vaadin.ui.controller.BuergerViewController$$Lambda$24/17735137.accept(Unknown Source)
```

**Comment by FabianWilms** [comment]
Nicht der ViewChange löst den Fehler aus, das Problem ist, dass der Login anscheinend nicht korrekt durchgeführt wird beim ersten mal. Dadurch schlagen dann sämtliche Zugriffe auf die API fehl.

//Edit:
Kleine Erweiterung: Der Fehler tritt nur dann auf, wenn die GUI neu gebaut wird, während man sich noch auf der "Bürger Pflege"-Seite befindet. Ist man bereits ausgelogt, oder befindet sich auf der Hauptseite tritt das Problem nach erneutem build nicht auf.
