### ISSUE TITLE
Audit von Änderungen

### ISSUE THREAD

**Issue by darenegade** [xdoo/vaadin-demo#51]
Als Nutzer möchte ich erkennen, wann - wer - welche Änderungen an den Datensätzen vorgenommen hat.

Stichwort: Hibernate / Auditing

**Comment by xdoo** [comment]
Bitte hier auch die Altlasten aus <code>de.muenchen.demo.service.domain.SecurityEntity</code> aufräumen.

**Comment by FabianWilms** [comment]
@Arne2

**Comment by martku** [comment]
Siehe: http://docs.jboss.org/envers/docs/ (Link von Claus aus #3)

**Comment by FabianWilms** [comment]
@xdoo Im BaseEntity hast du den Mandanten mit @NotAudited annotiert. Gibt es dafür einen Grund oder kann ich das entfernen?

**Comment by xdoo** [comment]
Frage mal bitte Bilel, ob er einen Grund sieht. Ich kann mich nicht mehr erinnern.

**Comment by FabianWilms** [comment]
Hab die erlaubnis zum entfernen gekriegt ;-). Und jetzt erhol dich lieber!

**Comment by FabianWilms** [comment]
OK, ich glaube ich habe herausgefunden warum es NotAudited markiert war. Wenn der Mandant audited wird, zerschießt es den BuergerResourceAssembler.

javax.persistence.EntityNotFoundException: Unable to find de.muenchen.demo.service.domain.Mandant with id 2
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:183)
    at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:262)
    at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:176)
    at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:286)
    at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)
    at de.muenchen.demo.service.domain.Mandant_$$_jvst76c_10.getOid(Mandant_$$_jvst76c_10.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.dozer.util.ReflectionUtils.invoke(ReflectionUtils.java:323)
    at 
[...]
    at org.dozer.MappingProcessor.map(MappingProcessor.java:124)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:119)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
    at de.muenchen.demo.service.rest.api.BuergerResourceAssembler.toResource(BuergerResourceAssembler.java:67)
    at de.muenchen.demo.service.rest.api.BuergerResourceAssembler.assembleWithAllLinks(BuergerResourceAssembler.java:227)
    at de.muenchen.demo.service.rest.api.BuergerResourceAssembler.lambda$toResource$0(BuergerResourceAssembler.java:51)
    at de.muenchen.demo.service.rest.api.BuergerResourceAssembler$$Lambda$9/3984406.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at de.muenchen.demo.service.rest.api.BuergerResourceAssembler.toResource(BuergerResourceAssembler.java:50)
    at de.muenchen.demo.service.rest.BuergerController.findAudits(BuergerController.java:769)

[...]

Habe also die Annotation zunächst wieder reingenommen.

**Comment by FabianWilms** [comment]
Nun fehlt noch die Einbindung des AuditUserEntity in die GUI, danach ist dieses Issue solved.

**Comment by xdoo** [comment]
@FabianHoltkoetter was meinst du mit Einbindung in die GUI?

**Comment by FabianWilms** [comment]
Entschuldige, das war etwas schwammig formuliert. Bisher kann man über die GUI nur die altzustände des jeweiligen Bürgers einsehen, jedoch fehlt noch die Information, wann und von wem diese Änderung durchgeführt wurde.

**Comment by FabianWilms** [comment]
History ist jetzt implementiert. ALLE Änderungen werden jetzt in einer eigenen Table "AUDITING_USER_ENTITY" gespeichert, mit einem Typ der Änderung, Zeitstempel, Nutzer der die Änderung veranlasst hat und dem Entity das geändert wurde in JSON-Form.

Wenn man möchte, dass ein Entity gelogt wird, reicht es die Annotation @MUCAudited vor die Klasse zu setzen. Zusätzlich lässt sich auch einstellen bei welchen Events gelogt werden soll, die möglichen Settings sind als statische Variablen in MUCAudited abrufbar.
