### ISSUE TITLE
Lock auf Hibernate Search Index

### ISSUE THREAD

**Issue by xdoo** [xdoo/vaadin-demo#61]
Beim Bauen des Services treten durch die Tests ständig Hibernate Exceptions auf, da der Index gesperrt ist:

<pre>
org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/tmp/de.muenchen.demo.service.domain.User/write.lock
    at org.apache.lucene.store.Lock.obtain(Lock.java:89)
    at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:755)
    at org.hibernate.search.backend.impl.lucene.IndexWriterHolder.createNewIndexWriter(IndexWriterHolder.java:131)
    at org.hibernate.search.backend.impl.lucene.IndexWriterHolder.getIndexWriter(IndexWriterHolder.java:97)
    at org.hibernate.search.backend.impl.lucene.AbstractWorkspaceImpl.getIndexWriter(AbstractWorkspaceImpl.java:112)
    at org.hibernate.search.backend.impl.lucene.LuceneBackendQueueTask.applyUpdates(LuceneBackendQueueTask.java:81)
    at org.hibernate.search.backend.impl.lucene.LuceneBackendQueueTask.run(LuceneBackendQueueTask.java:47)
    at org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.applyChangesets(SyncWorkProcessor.java:145)
    at org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:135)
    at java.lang.Thread.run(Thread.java:745)

2015-08-21 08:02:49.323 ERROR 10520 --- [ice.domain.User] o.h.s.b.i.lucene.LuceneBackendQueueTask  : HSEARCH000072: Couldn't open the IndexWriter because of previous error: operation skipped, index ouf of sync!
2015-08-21 08:02:49.579  INFO 10520 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat-2].[localhost].[/]     : Initializing Spring FrameworkServlet 'dispatcherServlet'
2015-08-21 08:02:49 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
2015-08-21 08:02:49 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 11 ms
2015-08-21 08:02:49 [http-nio-8080-exec-1] INFO  o.s.b.a.audit.listener.AuditListener - AuditEvent [timestamp=Fri Aug 21 08:02:49 CEST 2015, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Zugriff verweigert}]
2015-08-21 08:02:49 [http-nio-8080-exec-2] INFO  o.s.b.a.audit.listener.AuditListener - AuditEvent [timestamp=Fri Aug 21 08:02:49 CEST 2015, principal=hans, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null}]
2015-08-21 08:02:51.048 ERROR 10520 --- [ice.domain.User] o.h.s.exception.impl.LogErrorHandler     : HSEARCH000058: Exception occurred org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/tmp/de.muenchen.demo.service.domain.User/write.lock
Primary Failure:
    Entity de.muenchen.demo.service.domain.User  Id 165  Work Type  org.hibernate.search.backend.DeleteLuceneWork
Subsequent failures:
    Entity de.muenchen.demo.service.domain.User  Id 166  Work Type  org.hibernate.search.backend.DeleteLuceneWork
</pre>

Das Thema wird auch hier diskutiert:
http://stackoverflow.com/questions/10248598/clearing-locks-between-junit-tests-in-hibernate-search-4-1

**Comment by FabianWilms** [comment]
Dies tritt nur auf solange der MicroService noch läuft. Wird der MicroService zunächst beendet und dann die Tests gestarte gibt es keine Probleme.
